version: "3"
services:
  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      tagadata-network:
        aliases:
          - postgresForTagadata
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      APP_DATABASE_USER: ${APP_DATABASE_USER}
      APP_DATABASE_PASSWORD: ${APP_DATABASE_PASSWORD}
      APP_DATABASE_HOST: ${APP_DATABASE_HOST}
    networks:
      - tagadata-network
networks:
  tagadata-network:
    driver: bridge
